### ISSUE TITLE
First Sprint Doc - YUSHI

### ISSUE THREAD

**Issue by mengyushi** [mengyushi/dms297p#4]
https://docs.google.com/document/d/1bXXU7CwVooyd6thg1-SbyRLN9wF2bPs2OUrSTs-EWi8/edit?pli=1#
Parts assigned to @mengyushi:

- [x] High Level Diagram
- [x] SYSTEM MODELS
- [x] APPENDICES

**Comment by mengyushi** [comment]
DONE

**Comment by mengyushi** [comment]
Review Requested @hanroro @FEIHONGQIAN

**Comment by FEIHONGQIAN** [comment]
Reviewed. Elaborated.
