### ISSUE TITLE
First Sprint Doc - Han

### ISSUE THREAD

**Issue by mengyushi** [mengyushi/dms297p#5]
https://docs.google.com/document/d/1bXXU7CwVooyd6thg1-SbyRLN9wF2bPs2OUrSTs-EWi8/edit?pli=1#
Parts assigned to @hanroro:

- [x] Project Goals

- [x] User Interaction and Design

- [x] Coding and Testing

**Comment by hanroro** [comment]
Done.

**Comment by FEIHONGQIAN** [comment]
reviewed
