### ISSUE TITLE
First Sprint Doc - FEIHONG

### ISSUE THREAD

**Issue by mengyushi** [mengyushi/dms297p#6]
https://docs.google.com/document/d/1bXXU7CwVooyd6thg1-SbyRLN9wF2bPs2OUrSTs-EWi8/edit?pli=1#
Parts assigned to @FEIHONGQIAN:

- [x] Assumptions
- [x] User Stories and Use Cases

**Comment by FEIHONGQIAN** [comment]
Done

**Comment by mengyushi** [comment]
Reviewed
![image](https://user-images.githubusercontent.com/31721073/97249898-0599ec80-17c2-11eb-81d4-9cfa9e8d94f9.png)
