### ISSUE TITLE
Ruby on Rails bootcamp

### ISSUE THREAD

**Issue by mengyushi** [mengyushi/dms297p#7]
Task | Expected Duration | DUE 
------------ | ------------- | ------------- 
Getting start with Ruby on Rails (https://guides.rubyonrails.org/getting_started.html) | 5d | Oct 27
Ruby on Rails Architectural (https://adrianmejia.com/ruby-on-rails-architectural-design/) | 3d | Oct 30
Getting Started on Heroku with Ruby (https://devcenter.heroku.com/articles/getting-started-with-ruby) | 3d | Nov 2

**Comment by hanroro** [comment]
Finished task Getting start with Ruby on Rails.

**Comment by hanroro** [comment]
Finished task Getting Started on Heroku with Ruby.

**Comment by FEIHONGQIAN** [comment]
Finished task Getting start with Ruby on Rails.
